Fix issues related to new Pandas version
EducationalTestingService/rsmtool pull request #535
Opened 2021-07-09 20:12 UTC by aloukina

This PR addresses #534  and #533  

* Fixed test set up in TestAnalyzer
* Changed read_jsonlines to accommodate new behavior of `pd.normalize_json`

2021-07-09 20:33 UTC, aloukina commented
I kept the error catching in `read_jsonlines` for compatibility with earlier Pandas version: that line won't be covered by tests.

2021-07-12 14:36 UTC, desilinguist requested changes
Looks great! Just some minor tweaks to the code comments.

2021-07-12 14:36 UTC, desilinguist commented on rsmtool/reader.py
> +            # in this case we simply copy the column
```suggestion
            # Starting with Pandas v1.3, we get an empty data frame
            # if the column does not contain a nested json. 
            # If this is the case, we simply copy the column.
```

2021-07-12 14:36 UTC, desilinguist commented on rsmtool/reader.py
> +        # we'll catch that too
```suggestion
        # Pandas <v1.3 will raise an attribute error instead, 
        # so we'll catch that too
```

2021-07-15 21:01 UTC, pep8speaks commented
Hello @aloukina! Thanks for updating this PR. 





* In the file [`rsmtool/reader.py`](https://github.com/EducationalTestingService/rsmtool/blob/616f9ef965d8a480378901e1a9dcfc373ccb61a9/rsmtool/reader.py):

> [Line 71:60](https://github.com/EducationalTestingService/rsmtool/blob/616f9ef965d8a480378901e1a9dcfc373ccb61a9/rsmtool/reader.py#L71): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace

2021-07-15 21:04 UTC, aloukina commented
Thank you, @desilinguist  - all fixed!

2021-07-15 21:39 UTC, desilinguist approved these changes

2021-07-15 22:19 UTC, merged