Feature/conf matrix double scored data
EducationalTestingService/rsmtool pull request #649
Opened 2023-08-24 19:39 UTC by mulhod

Add in h1/h1 confusion matrix in reports.

Still a draft for the moment.

You can try it out on the `rsmtool` examples.

2023-08-24 21:27 UTC, desilinguist commented on rsmtool/analyzer.py
> +
```suggestion
        # compute a human1-human2 confusion matrix, if possible
        if include_second_score:
            df_preds_second_score_double_scored = df_preds_second_score.copy().dropna(
                subset=["sc1", "sc2"]
            )
            human1_scores = df_preds_second_score_double_scored["sc1"].round().astype("int64")
            human2_scores = df_preds_second_score_double_scored["sc2"].round().astype("int64")
            conf_matrix_h1h2 = confusion_matrix(human1_scores, human2_scores)
            labels = sorted(pd.concat([human1_scores, human2_scores]).unique())
            df_confmatrix_h1h2 = pd.DataFrame(
                conf_matrix_h1h2, index=labels, columns=labels
            ).transpose()

```

2023-08-24 21:29 UTC, desilinguist commented on rsmtool/analyzer.py
> +                )
```suggestion
```

2023-08-24 21:29 UTC, desilinguist commented on rsmtool/analyzer.py
> +            human2_scores = df_preds_second_score_double_scored["sc2_round"].astype("int64")
```suggestion
            human1_scores = df_preds_second_score_double_scored["sc1"].round().astype("int64")
            human2_scores = df_preds_second_score_double_scored["sc2"].round().astype("int64")
```

2023-08-24 21:31 UTC, desilinguist requested changes
Looks great! Just a couple of minor suggestions ...

2023-08-24 21:33 UTC, desilinguist commented
@mulhod you will also need to:
- update the [documentation](https://rsmtool.readthedocs.io/en/v11.0.1/usage_rsmtool.html#human-human-consistency) to include the new output file in the intermediate outputs. 
- update the intermediate files notebook to link to the new file.
-

2023-08-25 03:38 UTC, mulhod commented
> @mulhod you will also need to:
> 
> * update the [documentation](https://rsmtool.readthedocs.io/en/v11.0.1/usage_rsmtool.html#human-human-consistency) to include the new output file in the intermediate outputs.
> * update the intermediate files notebook to link to the new file.

I have addressed point #1. #2 is already addressed, I think (I didn't have to do anything special for this, I believe):
<img width="369" alt="Screenshot 2023-08-24 at 11 36 38 PM" src="https://github.com/EducationalTestingService/rsmtool/assets/5219803/63b787a5-8660-4e9e-9e37-eedeb2c48ec7">

2023-08-25 12:07 UTC, desilinguist approved these changes
LGTM!

2023-08-25 12:08 UTC, desilinguist commented
@tamarl08 do you mind taking a look as well?

2023-08-25 13:55 UTC, tazin-afrin approved these changes
Looks good to me too!

2023-08-25 14:05 UTC, desilinguist commented
Yes, I missed that! I see it twice too.

2023-08-25 14:06 UTC, mulhod commented
@tamarl08 Good catch! I see what's happening. Minor issue.

2023-08-25 14:14 UTC, tamarl08 approved these changes

2023-08-25 14:43 UTC, merged